name: Python Testing

on:
  push:
    branches:
      - main   # Or your default branch (could be 'master')
  pull_request:
    branches:
      - main   # Or your default branch (could be 'master')

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure pytest is in your requirements.txt

      # Step 4: Set PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run tests