name: Python Linting

on:
  push:
    branches:
      - main   # Or your default branch (could be 'master')
  pull_request:
    branches:
      - main   # Or your default branch (could be 'master')

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8   # Install flake8 for linting

      # Step 4: Run flake8 to check for linting errors
      - name: Run flake8
        run: |
          flake8 . --max-line-length=79  # Customize your flake8 command as needed
